_LVOReadJoyPort	equ -30
_LVOGetLanguageSelection	equ -36
_LVOGetKey	equ -48
_LVOQueryKeys	equ -54
_LVOAddKBInt	equ -60
_LVORemKBInt	equ -66
_LVOSystemControlA	equ -72
_LVOAddTimerInt	equ -78
_LVORemTimerInt	equ -84
_LVOStopTimerInt	equ -90
_LVOStartTimerInt	equ -96
_LVOElapsedTime	equ -102
_LVOAddVBlankInt	equ -108
_LVORemVBlankInt	equ -114
_LVOSetJoyPortAttrsA	equ -132
